### ISSUE TITLE
[Server] Add auth extension on handler

### ISSUE THREAD

**Issue by gwanryo** [bbconfhq/kiaranote#15]
## Feature Suggestion
* Add parameter on BaseHandler, for example, `role` for auth
* `role` will be one of role in role enums in [`RoleGuest`, `RoleUser`, `RoleAdmin`, ...]

## Auth Process using Role
* If `RoleGuest`
  * BaseHandler will not get `user_id` and `role` from session
  * return true always
* If `RoleUser`
  * BaseHandler will get `user_id` and `role` from session
  * return `true` if `role` is larger than `RoleUser`
* If `RoleAdmin`
  * Same as `RoleUser`
  * return `true` if `role` is larger than `RoleAdmin`

**Comment by gwanryo** [comment]
@blurfx 비행기에서 해주세요

**Comment by blurfx** [comment]
closed by #17
